### ISSUE TITLE
license ?

### ISSUE THREAD

**Issue by yannsucc** [5Mixer/mphx#15]
what's the license of this library ? MIT license ? (https://opensource.org/licenses/MIT)

**Comment by 5Mixer** [comment]
Yep, MIT!

HxNet was MIT, and some HxNet code is still lying around, so that definitely makes it MIT. I think stuff like this ought to be open and free.

**Comment by hamaluik** [comment]
It would be handy if there was a LICENSE file in the repo. Without seeing one, I assume I cannot use the code (see https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license), and can just look at it.

**Comment by 5Mixer** [comment]
Thanks for the info! I've added one, I think it's in the correct format. Thanks for raising the issue!
