### ISSUE TITLE
[flash] crash

### ISSUE THREAD

**Issue by yannsucc** [5Mixer/mphx#20]
crash when closing the server before closing the client on mphx.client.tcpFlashClient.hx

```
    public function isConnected():Bool
    {
        return m_client.connected;//cnx != null && cnx.isOpen();
    }
```

must be : 

```
    public function isConnected():Bool
    {
        return m_client!=null && m_client.connected;//cnx != null && cnx.isOpen();
    }
```

**Comment by 5Mixer** [comment]
Oh, yeah. Sorry, I think I Changed that when I was trying to get it to work. Meant to change it back. I have seen all, this issue, thanks! I just need to find time to be able to jump on my computer. I'll try to work with your suggestions this weekend. Thanks!

**Comment by yannsucc** [comment]
fixed with this pull request : https://github.com/5Mixer/mphx/pull/21
