### ISSUE TITLE
Rename TCP folder

### ISSUE THREAD

**Issue by 5Mixer** [5Mixer/mphx#23]
The TCP folder was in luxe but is irrelevent now. I think a better package name would be 'connection/s' because really, that's what it contains. All classes extend from 'Connection' except for 'NetSock' and I would argue that NetSock is directly linked to connections.

**Comment by yannsucc** [comment]
Done in this pull request :

https://github.com/5Mixer/mphx/pull/24

**Comment by 5Mixer** [comment]
Great stuff. The other /impl/ folders structures are fantastic too.
