### ISSUE TITLE
Issue running  the examples

### ISSUE THREAD

**Issue by ghost** [5Mixer/mphx#28]
Hi
I've downloaded the examples and when I try to run them i get the following message:
`haxe main.hxml`

> Main.hx:2: characters 7-34 : Type not found : mphx.server.impl.Server;

Same for all references to the library. I can however, access the dependency library(msgpack). 

I have tried to compile a test-file myself but am getting the same errors.
I've tried removing and reinstalling the library but with no luck.

Thank you!

> package ;
> import mphx.connection.IConnection;
> import mphx.server.impl.FlashServer;
> import mphx.server.impl.Server;
> import mphx.server.room.Room;
> 
> class Main {
>   public function new (){
>       var ip = "127.0.0.1";
>       var s = new Server(ip, 8000);
>   }
> 
>   public static function main (){
>       new Main();
>   }
> }

**Comment by 5Mixer** [comment]
Hi there! Thanks for trying the lib out. I've been flat out with exams at school so I've been pretty slack with updating it. I'm not sure how you installed mphx, but if you went through haxelibs version (`haxelib install mphx`) you could have a faulty version. (My fault, for not checking it's functionality). Could you try removing (`haxelib remove mphx`) and installing through git? `haxelib git mphx https://github.com/5Mixer/mphx.git`. 

I'll do further work tonight. Thanks!

**Comment by ghost** [comment]
@5Mixer That did the trick! Thank you!

**Comment by PXshadow** [comment]
THANK YOU SO MUCH. I had it working and then stopped working for 5 days while I pulled out my hair.
