### ISSUE TITLE
Problem with the server creation

### ISSUE THREAD

**Issue by reaperspeeds** [5Mixer/mphx#42]
Hi, I am trying to implement the extension in android/ios  but it doesn't work
i noticed you start the server in a console script (for some targets like neko) 
but how do you start the server in android/ios?

If the server is created manually (by console), the client works, 
but if the server is created through the app, it stops the app...

what is the correct way to use it on android-ios?
thanks

**Comment by ghost** [comment]
Forgive me if i'm mistaken but it sounds like you're trying to run the server on a mobile device? That's not possible. The client code is meant to run on the device, not the backend(server) code. 
If this is the case, then I think we can close this as an none-issue. :) 

Also, please note that running mphx on a tablet/phone hasn't been thoroughly tested.

**Comment by 5Mixer** [comment]
And just to quickly add to that, even for the client side, it has never been tested on a mobile device. I'd like for it to work, but it's complex to maintain as a stable target, as testing isn't as easy. How functional it is on mobile is really up to how well general haxe sockets work on mobile, without changes. In this configuration, (and I guess this is true for all of the project) mphx acts as a big wrapper around typical haxe socket implementations, adding things like rooms and abstracting away listener connections. This is why any bug haxe sockets have, mphx has. This is different to something like a c++ extern library, which is separate from the socket implementations haxe has.

With that being said, mobile would be a nice target.

**Comment by yannsucc** [comment]
i tested a Flash Client packaged into iOS/android with Air3 with a Mphx client, connecting to a distant C++/neko server and it's working fine, but not running a server from a mobile.

**Comment by 5Mixer** [comment]
I'm thinking I can close this? I don't see server hosting on mobile as a big priority. I'm more interested in if the client works on mobile, as the server is really meant to run on a desktop server.
