### ISSUE TITLE
Incompatible with upcoming 3.4 (ie. haxe nightly)

### ISSUE THREAD

**Issue by sneurlax** [5Mixer/mphx#49]
Hi, I know you have that big ol' disclaimer saying that 3.3.0 is unsupported, but I'd like to note that the current nightly haxe build (the upcoming 3.4) is currently broken as well.  Which is a shame, as this lib seems great.

**Comment by 5Mixer** [comment]
Oh no! Sorry to hear you're having trouble. I'd like to resolve this issue, but can't reproduce it. I just downloaded Haxe 3.4.1 and ran the Basic/Simple example successfully on neko. What platform/example were you working with, and if you were targetting neko, would you mind running `neko` and sharing the version?

Thanks very much, sorry I didn't notice the issue earlier!
