### ISSUE TITLE
Event Order

### ISSUE THREAD

**Issue by Gulvan0** [5Mixer/mphx#53]
If I send events one after another, should I expect that the recipient may receive it in the wrong order?

**Comment by 5Mixer** [comment]
They _should_, but there aren't any checks in place that guarantee it. I'd say it depends on the reliability of the network, size of the packets, etc.

If it's something you do need to guarantee, you'll have to build on top of the protocol. For instance, a rudimentary order check might be to give each message sent to a client an incremented message number - if the number is not an increment of the previous received message, a message might have been missed, or is still in transit. mphx doesn't sign any messages or do event order handling; it is primarily targeted at the creation of small games where packet order isn't really worth the overhead.

For what it's worth, I haven't worked on this library in a very long time and it may have issues.

**Comment by Gulvan0** [comment]
Hmmm
In fact, I made an investigation yesterday and got multiple contradicting answers.
[Here](https://stackoverflow.com/questions/11804721/can-websocket-messages-arrive-out-of-order) are the answers about both websockets and TCP. They say that the wrong message order is impossible to achieve because the second message's bytes are sent later than the first one's. 
However, some people (including you) say that theoretically, messages can arrive in the wrong order.
I'm a bit confused

**Comment by Gulvan0** [comment]
[And another](https://stackoverflow.com/questions/1691179/is-tcp-guaranteed-to-arrive-in-order)
"As long as the two messages were sent on the same TCP connection, order will be maintained. If multiple connections are opened between the same pair of processes, you may be in trouble"

I'm using the same connection throughout all the game session.

**Comment by 5Mixer** [comment]
Ah, my mistake. The links you've attached seem to certify that TCP and hence mphx provides guarantees as to packet order. Just clarifying however, "because the second message's bytes are sent later than the first one's" - I don't believe this is why it is impossible. TCP must include order checking as part of the protocol, otherwise I do think order errors could occur (ie. you might have to be more careful if mphx used UDP and not TCP).

So that should clarify things - you're fine.

**Comment by Gulvan0** [comment]
Thank you
By the way, thanks for a great lib. I'm using it for over a year now
