### ISSUE TITLE
profiles

### ISSUE THREAD

**Issue by TheRealFowluhh** [5Mixer/mphx#59]
hi uhhhhh

are profiles/accounts supported
for cool game

**Comment by 5Mixer** [comment]
There isn't any inbuilt support for profiles or accounts - mphx is purely to simplify networking.

Authentication can be a fairly involved area and I'm not aware of any mphx projects that use it. The one part of authentication that mphx might need to be responsible for - over the network encryption - is currently not supported.

For simple games without passwords, one possible implementation of profiles could be
 - When the client starts, it checks if a locally stored token exists. If it doesn't, it generates one (a long sequence of random characters).
 - This token is sent to the server in an initial connection message. The server looks in a database or generic store to see if profile information for that token exists. If it does, it can be sent to the client and associated with the connection, if not, a new database entry is made.
 - Player username, scores, items, etc are stored by the server based on the client key.

This is just off the top of my head, and isn't perfect (for example the client can't easily login from another computer without the saved token). Of course you could do simple username/password based authentication too, but without encryption, users passwords would be visible by anyone intercepting network traffic - don't do this :) Other libraries may have encryption support.
