### ISSUE TITLE
Use Haxe serialization?

### ISSUE THREAD

**Issue by anissen** [5Mixer/mphx#7]
Is there any reason why you don't use [Haxe serialization/deserialization](http://haxe.org/manual/std-serialization.html) for instead of `haxe.Json.stringify`? I believe the built-in serialization is both faster, smaller and able to serialize/deserialize complex objects.

**Comment by 5Mixer** [comment]
You're absolutely right. There's even a serialiser called message-pack (already listed as a dependency, but unused in code). Apparently this serialises things smaller than JSON can. Either way, I think it should be changed. It would be interesting to see the performance difference.

I'll do this quickly tonight. :)

**Comment by 5Mixer** [comment]
I've thought about this today, and one thing that I really want is this library to remain open. That means being able to use it with and without websockets, with different libraries, etc. I think something that it would be nice to keep open (despite me thinking that this use case is unlikely) a haxe server and pure javascript client. Even if the library isn't used in this way, by not allowing JSON object handling, it restricts the possibility of that use case entirely.

So, I've changed it to use Haxe Serialization for now (85cfd2a5b), but I'm thinking that being able to change the serializer is a good goal.

**Comment by 5Mixer** [comment]
Alright, this is pretty much resolved (de6e60a6f97). There is an implementation for raw JSON and for haxe serialization, with haxe serialization being default.

Thanks for raising the issue!

**Comment by anissen** [comment]
That sounds like a good solution without complicating the library too much :+1:
